### ISSUE TITLE
Cannot install using composer

### ISSUE THREAD

**Issue by wasimkham** [pawelmysior/laravel-freshmail#1]
Says it can't find the package, any idea why?

```
▶ composer require pawelmysior/freshmail 

  [InvalidArgumentException]
  Could not find package pawelmysior/freshmail at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

**Comment by pawelmysior** [comment]
Oh, sorry my friend, I'm not actually actively developing this package. The only option that's available at the moment is adding a new email address to the list. It definitely not a stable package 😉

Still if you want to use it, try putting this in your `package.json`:

    "pawelmysior/freshmail": "dev-master"

Best regards.

**Comment by wasimkham** [comment]
Ah ok cool thanks :)
